// Pixel art sprite data for Mona the cat-topus (cat + octopus tentacles)
// 20x20 text grids for detail while staying performant

const PAL = {
  transparent: 'rgba(0,0,0,0)',
  black: '#1a1a2e',
  darkGray: '#3d3d5c',
  gray: '#7a7a9e',
  white: '#f0f0f8',
  orange: '#ff8c42',
  orangeDark: '#d96a20',
  orangeLight: '#ffaa66',
  eye: '#2ecc71',
  eyeDark: '#1a9c54',
  pink: '#ff6b9d',
  pinkDark: '#d94a7a',
  purple: '#9b59b6',
  purpleDark: '#7b3f96',
  blue: '#3498db',
  yellow: '#f1c40f',
  red: '#e74c3c',
  green: '#2ecc71',
  tentacle: '#8e44ad',
  tentLight: '#af7ac5',
  tentDark: '#6c3483',
};

const C: Record<string, string> = {
  '.': PAL.transparent,
  'k': PAL.black,
  'd': PAL.darkGray,
  'g': PAL.gray,
  'w': PAL.white,
  'o': PAL.orange,
  'O': PAL.orangeDark,
  'L': PAL.orangeLight,
  'e': PAL.eye,
  'E': PAL.eyeDark,
  'p': PAL.pink,
  'P': PAL.pinkDark,
  'u': PAL.purple,
  'U': PAL.purpleDark,
  't': PAL.tentacle,
  'T': PAL.tentLight,
  'D': PAL.tentDark,
  'b': PAL.blue,
  'y': PAL.yellow,
  'r': PAL.red,
  'G': PAL.green,
  's': PAL.gray,
};

// ========== MONA IDLE (4 frames) ==========
// Cat face with pointy ears, big green eyes, cute nose, tentacles hanging below body

const MONA_IDLE_1 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_IDLE_2 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koookkkkkkoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
...kt..kk..tk.......
...t........t.......
....................
....................
`;

const MONA_IDLE_3 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kT...kk...Tk......
..t..........t......
....................
....................
`;

const MONA_IDLE_4 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koookkkkkkoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..ktddddddddtk.....
..kTt.kkkk.tTk......
...kt..kk..tk.......
....t......t........
....................
....................
`;

// ========== MONA WALK (4 frames) ==========
const MONA_WALK_1 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
..kkdddddddddkk....
..kt.kkddddkttk....
..ktt..kk..kttk....
...t....kk..t.......
....................
....................
....................
`;

const MONA_WALK_2 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..ktkdddddddkTk....
..ktt.kk.kk.ttk....
...t..kk..kk.t.....
....................
....................
....................
`;

const MONA_WALK_3 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kkddddddddkk....
..kttkkddddkttk....
..ktt.kk..k.Ttk....
...t..kk.....t......
....................
....................
....................
`;

const MONA_WALK_4 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..kTkdddddddktk....
..ktt.kk.kk.ttk....
...t..kk..kk.t.....
....................
....................
....................
`;

// ========== MONA CODE (4 frames - typing animation) ==========
const MONA_CODE_1 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
..bbkoooooooook.....
.bbbkddoooooddk.....
..b.kdddddddddk....
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_CODE_2 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooookbb...
...kddoooooddkbbb..
...kdddddddddk.b...
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_CODE_3 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
.bbbkoooooooook.....
.bb.kddoooooddk.....
..b.kdddddddddk....
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_CODE_4 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....kooooooookbbb...
...kddoooooddk.bb...
...kdddddddddk.b...
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

// ========== MONA SPELL / TERMINAL (4 frames) ==========
const MONA_SPELL_1 = `
........uu..........
.....kkuuukk........
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
..Tkkoooooooooktt...
.TTTkddoooooddkTTT.
..T.kdddddddddk.T..
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_SPELL_2 = `
.......uuuu.........
....u.kkuukk........
....koOk..koOk.u....
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
.tTkkoooooooookTt...
TTTTkddoooooddkTTTT
.TT.kddddddddkTT...
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_SPELL_3 = `
......uuuuuu........
...uu.kkuukk.u......
....koOk..koOk......
...koooOkkOoook.u...
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
..TkkoooooooookT....
.TTTkddoooooddkTTT.
..T.kdddddddddk.T..
...kdddddddddk.....
..kTddddddddTk.....
..kTt.kkkk.tTk......
..kT...kk...Tk......
...T........T.......
....................
....................
`;

const MONA_SPELL_4 = `
.......uuuu.........
.....kkuuukk........
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
.ttkkoooooooooktt...
.TTTkddoooooddkTTT.
..T.kdddddddddk.T..
...kdddddddddk.....
..ktddddddddtk.....
..kTt.kkkk.tTk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

// ========== MONA FIGHT (4 frames - tentacle swipe!) ==========
const MONA_FIGHT_1 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooopPoooook......
...koooooooooook....
...kkoooooooookk....
....koooooooook.t...
...kddoooooddk.tTk..
...kdddddddddk.tT..
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_FIGHT_2 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooopPoooook......
...koooooooooook....
...kkoooooooookk.tT.
....koooooooook.tTk.
...kddoooooddk..tT..
...kdddddddddk.....
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_FIGHT_3 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook.tTT
..kooopPoooook..tTk.
...koooooooooook.t..
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

const MONA_FIGHT_4 = `
....................
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooeekkeeoook....
..koookk..kkoook....
..kooopPoooook......
...koooooooooook....
...kkoooooooookk....
....koooooooook..t..
...kddoooooddk..tTk.
...kdddddddddk.tT..
...kdddddddddk.....
..ktddddddddtk.....
..ktt.kkkk.ttk......
..kt...kk...tk......
...t........t.......
....................
....................
`;

// ========== MONA CELEBRATE (4 frames) ==========
const MONA_CELEBRATE_1 = `
.........yy.........
.....kk.yykk........
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooweeweoook.....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..kTddddddddTk.....
..kTt.kkkk.tTk......
..kT...kk...Tk......
...T........T.......
....................
....................
`;

const MONA_CELEBRATE_2 = `
..yy..........yy....
.....kk....kk.......
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooweeweoook.....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
..kkdddddddddkk....
..kt.kdddddk.tk....
..ktt..kk..kttk....
...t...kk...t.......
...T........T.......
....................
....................
....................
`;

const MONA_CELEBRATE_3 = `
....yy....yy........
.....kk.yykk........
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooweeweoook.....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
...kdddddddddk.....
..kTddddddddTk.....
..kTt.kkkk.tTk......
...T...kk...T.......
....................
....................
....................
`;

const MONA_CELEBRATE_4 = `
....................
..yy.kk....kk.yy...
....koOk..koOk......
...koooOkkOoook.....
...koooooooooook....
..koooweeweoook.....
..koookk..kkoook....
..kooooopoooook.....
...koooooooooook....
...kkoooooooookk....
....koooooooook.....
...kddoooooddk......
...kdddddddddk.....
..kkdddddddddkk....
..kt.kkddkkk.tk....
..kTt.kk..k.Ttk....
...T..kk....T.......
....................
....................
....................
`;

// ========== MONA DAMAGE (2 frames) ==========
const MONA_DAMAGE_1 = `
....................
......kk....kk......
.....koOk..koOk.....
....koooOkkOoook....
....koooooooooook...
...koookkkkkkoook...
...koookk..kkoook...
...kooooooooook.....
....koooooooooook...
....kkoooooooookk...
.....koooooooook....
....kddoooooddk.....
....kdddddddddk....
...kkdddddddddkk...
...kt.kdddddk.tk...
...ktt..kk...ttk....
....t........t......
....................
....................
....................
`;

const MONA_DAMAGE_2 = `
....................
....kk....kk........
...koOk..koOk.......
..koooOkkOoook......
..koooooooooook.....
.koookkkkkkoook.....
.koookk..kkoook.....
.kooooooooook.......
..koooooooooook.....
..kkoooooooookk.....
...koooooooook......
..kddoooooddk.......
..kdddddddddk......
..kdddddddddk......
.ktddddddddtk......
.ktt.kkkk.ttk.......
.kt...kk...tk.......
..t........t........
....................
....................
`;

// ========== MONA SLEEP (4 frames - curled up with ZZZ) ==========
const MONA_SLEEP_1 = `
....................
....................
....................
....................
....................
....................
..............b.....
.............b......
....................
.....kk..kk.........
....koookOoook......
...kookkkkkoook.....
..kooooooooooook....
..koooooooooook.....
..kdddddddddddk....
..ktttttttttttk.....
...kkkkkkkkkkkk.....
....................
....................
....................
`;

const MONA_SLEEP_2 = `
....................
....................
....................
....................
....................
..............b.....
.............b......
............b.......
....................
.....kk..kk.........
....koookOoook......
...kookkkkkoook.....
..kooooooooooook....
..koooooooooook.....
..kdddddddddddk....
..ktttttttttttk.....
...kkkkkkkkkkkk.....
....................
....................
....................
`;

const MONA_SLEEP_3 = `
....................
....................
....................
....................
..............b.....
.............b......
............b.......
....................
....................
.....kk..kk.........
....koookOoook......
...kookkkkkoook.....
..kooooooooooook....
..koooooooooook.....
..kdddddddddddk....
..ktttttttttttk.....
...kkkkkkkkkkkk.....
....................
....................
....................
`;

const MONA_SLEEP_4 = `
....................
....................
....................
..............b.....
.............b......
............b.......
....................
....................
....................
.....kk..kk.........
....koookOoook......
...kookkkkkoook.....
..kooooooooooook....
..koooooooooook.....
..kdddddddddddk....
..ktttttttttttk.....
...kkkkkkkkkkkk.....
....................
....................
....................
`;

// ========== ENEMY BUG (16x16 - red) ==========
const ENEMY_BUG = `
....................
....................
......rr..rr........
.....krrkkrrk.......
....krrrrrrrk.......
....krwrkwrrk.......
....krrrrrrrk.......
....krrrrrrrkk......
.....krrrrrrk.......
.....kkrrrkk........
......k.k.k........
.....k..k..k........
....................
....................
....................
....................
....................
....................
....................
....................
`;

// ========== WARNING BUG (smaller, yellow) ==========
const WARNING_BUG = `
....................
....................
....................
.......yy...........
......kyykk.........
.....kyyyryk........
.....kykkyyk........
.....kyyyyyyk.......
......kyyyryk.......
......kkykk.........
.......k.k..........
....................
....................
....................
....................
....................
....................
....................
....................
....................
`;

// ========== FURNITURE SPRITES (20x20) ==========

const DESK_COMPUTER = `
....................
....................
....kkkkkkkkkk......
....kbbbbbbbbk......
....kbbbbbbbbk......
....kbbbbbbbbk......
....kbbbbbbbbk......
....kkkkkkkkkk......
......k....k........
...kkkkkkkkkkkk.....
...kdddddddddk.....
...kdddddddddk.....
...kdddddddddk.....
...kk........kk.....
....................
....................
....................
....................
....................
....................
`;

const BOOKSHELF = `
....................
...kkkkkkkkkkk......
...kOoObbrOoOk......
...kOoObbrOoOk......
...kkkkkkkkkkk......
...krroObbOoOk......
...krroObbOoOk......
...kkkkkkkkkkk......
...kOoOrrOobbk......
...kOoOrrOobbk......
...kkkkkkkkkkk......
...kk........kk.....
....................
....................
....................
....................
....................
....................
....................
....................
`;

const FILING_CABINET = `
....................
....................
....kkkkkkkkk.......
....kdddddddk......
....kdd.dd.ddk......
....kkkkkkkkk.......
....kdddddddk......
....kdd.dd.ddk......
....kkkkkkkkk.......
....kdddddddk......
....kdd.dd.ddk......
....kkkkkkkkk.......
....kk.....kk.......
....................
....................
....................
....................
....................
....................
....................
`;

const EASEL = `
....................
....................
.......kkk..........
......kppbk.........
......kpbbk.........
......kbppk.........
......kkkkk.........
.......k.k..........
......k...k.........
.....k.....k........
....k.......k.......
....................
....................
....................
....................
....................
....................
....................
....................
....................
`;

const COFFEE_CUP = `
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
........g...........
.......kOOk.........
.......kOOkk........
.......kOOkk........
........kkk.........
....................
....................
`;

const DOOR = `
....................
....................
..kkkkkkkkkk........
..kOOOOOOOOk........
..kOOOOOOOOk........
..kOOOOOOOOk........
..kOOOOOOOOk........
..kOOOOOyOOk........
..kOOOOOOOOk........
..kOOOOOOOOk........
..kOOOOOOOOk........
..kOOOOOOOOk........
..kOOOOOOOOk........
..kkkkkkkkkk........
....................
....................
....................
....................
....................
....................
`;

function parseSprite(data: string): string[][] {
  return data.trim().split('\n').map(row =>
    row.split('').map(ch => C[ch] || C['.'])
  );
}

function renderSpriteToCanvas(pixels: string[][], size: number): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  const pixelW = size / pixels[0].length;
  const pixelH = size / pixels.length;
  for (let y = 0; y < pixels.length; y++) {
    for (let x = 0; x < pixels[y].length; x++) {
      if (pixels[y][x] !== C['.']) {
        ctx.fillStyle = pixels[y][x];
        ctx.fillRect(Math.floor(x * pixelW), Math.floor(y * pixelH), Math.ceil(pixelW), Math.ceil(pixelH));
      }
    }
  }
  return canvas;
}

export interface SpriteAnimation {
  frames: HTMLCanvasElement[];
  frameRate: number;
  loop: boolean;
}

export interface SpriteSet {
  idle: SpriteAnimation;
  walk: SpriteAnimation;
  code: SpriteAnimation;
  spell: SpriteAnimation;
  fight: SpriteAnimation;
  celebrate: SpriteAnimation;
  damage: SpriteAnimation;
  sleep: SpriteAnimation;
}

export interface EnemySprites {
  bug: HTMLCanvasElement;
  warning: HTMLCanvasElement;
}

export type FurnitureType = 'code' | 'data' | 'docs' | 'design' | 'default';

export interface FurnitureSprites {
  desk: HTMLCanvasElement;
  bookshelf: HTMLCanvasElement;
  cabinet: HTMLCanvasElement;
  easel: HTMLCanvasElement;
  coffee: HTMLCanvasElement;
  door: HTMLCanvasElement;
}

let cachedSprites: SpriteSet | null = null;
let cachedEnemySprites: EnemySprites | null = null;
let cachedFurniture: FurnitureSprites | null = null;
let cachedSize = 0;

export function getMonaSprites(size = 64): SpriteSet {
  if (cachedSprites && cachedSize === size) return cachedSprites;
  cachedSize = size;
  const r = (s: string) => renderSpriteToCanvas(parseSprite(s), size);
  cachedSprites = {
    idle: { frames: [r(MONA_IDLE_1), r(MONA_IDLE_2), r(MONA_IDLE_3), r(MONA_IDLE_4)], frameRate: 2, loop: true },
    walk: { frames: [r(MONA_WALK_1), r(MONA_WALK_2), r(MONA_WALK_3), r(MONA_WALK_4)], frameRate: 8, loop: true },
    code: { frames: [r(MONA_CODE_1), r(MONA_CODE_2), r(MONA_CODE_3), r(MONA_CODE_4)], frameRate: 6, loop: true },
    spell: { frames: [r(MONA_SPELL_1), r(MONA_SPELL_2), r(MONA_SPELL_3), r(MONA_SPELL_4)], frameRate: 4, loop: true },
    fight: { frames: [r(MONA_FIGHT_1), r(MONA_FIGHT_2), r(MONA_FIGHT_3), r(MONA_FIGHT_4)], frameRate: 8, loop: true },
    celebrate: { frames: [r(MONA_CELEBRATE_1), r(MONA_CELEBRATE_2), r(MONA_CELEBRATE_3), r(MONA_CELEBRATE_4)], frameRate: 4, loop: true },
    damage: { frames: [r(MONA_DAMAGE_1), r(MONA_DAMAGE_2)], frameRate: 6, loop: false },
    sleep: { frames: [r(MONA_SLEEP_1), r(MONA_SLEEP_2), r(MONA_SLEEP_3), r(MONA_SLEEP_4)], frameRate: 1, loop: true },
  };
  return cachedSprites;
}

export function getEnemySprites(size = 48): EnemySprites {
  if (cachedEnemySprites) return cachedEnemySprites;
  cachedEnemySprites = {
    bug: renderSpriteToCanvas(parseSprite(ENEMY_BUG), size),
    warning: renderSpriteToCanvas(parseSprite(WARNING_BUG), Math.floor(size * 0.7)),
  };
  return cachedEnemySprites;
}

export function getFurnitureSprites(size = 64): FurnitureSprites {
  if (cachedFurniture) return cachedFurniture;
  const r = (s: string) => renderSpriteToCanvas(parseSprite(s), size);
  cachedFurniture = {
    desk: r(DESK_COMPUTER),
    bookshelf: r(BOOKSHELF),
    cabinet: r(FILING_CABINET),
    easel: r(EASEL),
    coffee: r(COFFEE_CUP),
    door: r(DOOR),
  };
  return cachedFurniture;
}

export function getFurnitureType(filename: string): FurnitureType {
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  if (['ts', 'js', 'tsx', 'jsx', 'py', 'go', 'rs', 'java', 'c', 'cpp'].includes(ext)) return 'code';
  if (['json', 'yaml', 'yml', 'toml', 'xml', 'csv'].includes(ext)) return 'data';
  if (['md', 'txt', 'rst', 'adoc'].includes(ext)) return 'docs';
  if (['css', 'html', 'scss', 'less', 'svg'].includes(ext)) return 'design';
  return 'default';
}

export const TILE_COLORS = {
  floor: '#2c2c54',
  floorAlt: '#34345c',
  wall: '#1a1a2e',
  wallTop: '#2d2d5e',
  door: '#5c3d2e',
  doorFrame: '#8b6914',
};

// Mini Mona face for HUD (returns data URL)
export function getMonaFaceDataURL(): string {
  const mini = `
........
..kk.kk.
.koOkoOk
.koooook
.koekook
.koopook
..kookk.
...kk...
`;
  const canvas = renderSpriteToCanvas(parseSprite(mini), 16);
  return canvas.toDataURL();
}
